storageClass:
  name: gridgain
  ignite_wal_size: 1Gi
  ignite_work_size: 1Gi
  ignite_swap_size: 1Gi
  # type can be aws,gcp,azure or local
  type: local
  local:
    # update local path as per requirement
    path: /gridgain/data/
  gcp:
    provisioner: kubernetes.io/gce-pd
    parameters: { type: pd-ssd }
  aws:
    provisioner: kubernetes.io/aws-ebs
    parameters: { type: gp2,fsType: ext4 }
  azure:
    provisioner: kubernetes.io/azure-disk
    parameters: { kind: Managed,storageaccounttype: Premium_LRS }